export const options = {
  title_graphic: {
    section: "1. Main",
    type: "string",
    label: "1 Title",
  },
  default_icon: {
    section: "1. Main",
    type: "string",
    label: "2. Title Icon <i>",
    default: "",
  },
  font_size_title: {
    section: "2. Layout",
    type: "string",
    label: "1. Title Font Size",
    default: "11",
  },
  font_weight_title: {
    section: "2. Layout",
    type: "string",
    label: "2. Title Font Weight",
    display: "select",
    values: [{ normal: "normal" }, { bold: "bold" }],
    default: "normal",
  },
  font_family_title: {
    section: "2. Layout",
    type: "string",
    label: "3. Title Font Family",
    display: "select",
    values: [{ "'Quicksand', sans-serif": "'Quicksand', sans-serif" }],
    default: "'Quicksand', sans-serif",
  },
  font_color_title: {
    section: "2. Layout",
    type: "string",
    display: "color",
    label: "4. Title Font Color ",
    default: "#333333",
  },
  font_size: {
    section: "2. Layout",
    type: "string",
    label: "Chart Font Size",
    default: "11",
  },
  font_weight: {
    section: "2. Layout",
    type: "string",
    label: "Chart Font Weight",
    display: "select",
    values: [{ normal: "normal" }, { bold: "bold" }],
    default: "normal",
  },
  font_family: {
    section: "2. Layout",
    type: "string",
    label: "Chart Font Family",
    display: "select",
    values: [{ "'Quicksand', sans-serif": "'Quicksand', sans-serif" }],
    default: "'Quicksand', sans-serif",
  },
  font_color: {
    section: "2. Layout",
    type: "string",
    display: "color",
    label: "Chart Font Color",
    default: "#333333",
  },
  top_margin: {
    section: "2. Layout",
    type: "string",
    label: "Top margin (px)",
    default: "170",
  },
  bottom_margin: {
    section: "2. Layout",
    type: "string",
    label: "Chart Bottom margin (px)",
    default: "10",
  },
  left_margin: {
    section: "2. Layout",
    type: "string",
    label: "Chart Left margin (px)",
    default: "10",
  },
  right_margin: {
    section: "2. Layout",
    type: "string",
    label: "Chart Right margin (px)",
    default: "10",
  },
  border_radius: {
    section: "2. Layout",
    type: "string",
    label: "Chart Border Radius (px)",
    default: "5",
  },
  padding: {
    section: "2. Layout",
    type: "string",
    label: "Chart Padding (px)",
    default: "10",
  },
  value_color_selected: {
    section: "2. Layout",
    type: "string",
    display: "color",
    label: "Chart Font Color Selected",
    default: "#dedede",
  },
  value_background_selected: {
    section: "2. Layout",
    type: "string",
    display: "color",
    label: "Chart Background Selected",
    default: "#20B9FC",
  },
  background_onclick: {
    section: "2. Layout",
    type: "string",
    display: "color",
    label: "Chart Background onclick",
    default: "#dedede",
  },
  mouse_hover_background: {
    section: "2. Layout",
    type: "string",
    display: "color",
    label: "Chart Background Mouseover",
    default: "#dedede",
  },
  mouse_hover_color: {
    section: "2. Layout",
    type: "string",
    display: "color",
    label: "Chart Font Color Mouseover",
    default: "#dedede",
  },
  td_padding: {
    section: "2. Layout",
    type: "string",
    label: "Chart TD Padding (px)",
    default: "10",
  },
  height_wrapper: {
    section: "2. Layout",
    type: "string",
    label: "Chart Height Wrapper (%)",
    default: "70",
  },
  width_wrapper: {
    section: "2. Layout",
    type: "string",
    label: "Chart Width Wrapper (%)",
    default: "98",
  },
};
