export const options = {
  title_graphic: {
    section: "1. Main",
    type: "string",
    label: "1 Title",
  },
  default_icon: {
    section: "1. Main",
    type: "string",
    label: "2. Title Icon <i>",
    default: "",
  },
  dimension_title: {
    section: "1. Main",
    type: "string",
    label: "3. Dimension tooltip",
    default: "",
  },
  measure_title: {
    section: "1. Main",
    type: "string",
    label: "4. Measure tooltip",
    default: "",
  },
  chart_description: {
    section: "1. Main",
    type: "string",
    label: "5. Chart description",
    default: "",
  },
  thead_title_1: {
    section: "1. Main",
    type: "string",
    label: "6. Table Thead title 1",
    default: "",
  },
  thead_title_2: {
    section: "1. Main",
    type: "string",
    label: "7. Table Thead title 2",
    default: "",
  },
  color_not_selected: {
    section: "2. Layout",
    type: "string",
    display: "color",
    label: "Color when not selected",
    default: "#dedede",
  },
  color_table: {
    section: "2. Layout",
    type: "string",
    display: "color",
    label: "Table Bar Color",
    default: "#dedede",
  },
  table_font_size: {
    section: "2. Layout",
    type: "string",
    label: "Table Font Size",
    default: "11",
  },
  table_font_weight: {
    section: "2. Layout",
    type: "string",
    label: "Table Font Weight",
    display: "select",
    values: [{ normal: "normal" }, { bold: "bold" }],
    default: "normal",
  },
  table_font_family: {
    section: "2. Layout",
    type: "string",
    label: "Table Font Family",
    display: "select",
    values: [{ "'Quicksand', sans-serif": "'Quicksand', sans-serif" }],
    default: "'Quicksand', sans-serif",
  },
  table_font_color: {
    section: "2. Layout",
    type: "string",
    display: "color",
    label: "Table Font Color",
    default: "#333333",
  },
  number_format: {
    section: "4. Format",
    type: "string",
    label: "Number format",
    display: "select",
    values: [{ Percent: "percent" }, { Normal: "normal" }],
    default: "normal",
  },
  merge_selected_filters: {
    section: "4. Format",
    type: "string",
    label: "Merge selected filters",
    display: "select",
    values: [{ Yes: "yes" }, { No: "no" }],
    default: "no",
  },
  show_title: {
    section: "4. Format",
    type: "string",
    label: "Show title (thead)",
    display: "select",
    default: "no",
    values: [{ Yes: "yes" }, { No: "no" }],
  },
};
