export const vennOptions = {
  chart_type: {
    section: "1. Main",
    type: "string",
    label: "1. Chart type",
    default: "bar",
    display: "select",
    values: [
      { Bar: "bar" },
      { "Simple Bar": "bar_simple" },
      { "Pie|Donut": "donut" },
      { Banner: "banner" },
      { Insights: "insights" },
      { "Insights Measures": "insights_measures" },
      { Venn: "venn" },
      { Map: "map" },
      { Table: "bar_horizontal" },
      { "Bar measures only": "bar_simple_measure" },
      { "Button segment": "btn_segment" },
    ],
  },
  title_graphic: {
    section: "1. Main",
    type: "string",
    label: "2. Title",
  },
  // title_font_size: {
  //   section: "1. Main",
  //   type: "string",
  //   label: "3. Title font size",
  // },
  dimension_title: {
    section: "1. Main",
    type: "string",
    label: "3. Dimension title",
    default: "",
  },
  measure_title: {
    section: "1. Main",
    type: "string",
    label: "4. Measure title",
    default: "",
  },
  default_icon: {
    section: "1. Main",
    type: "string",
    label: "5. Title Icon <i>",
    default: "",
  },
  chart_description: {
    section: "1. Main",
    type: "string",
    label: "6. Chart description",
    default: "",
  },
  // side_margin: {
  //   section: "2. Layout",
  //   type: "string",
  //   label: "Left and right margin of the chart",
  //   default: "40",
  //   display: "select",
  //   values: [
  //     { 0: "0" },
  //     { 10: "10" },
  //     { 20: "20" },
  //     { 30: "30" },
  //     { 40: "40" },
  //     { 50: "50" },
  //     { 60: "60" },
  //     { 70: "70" },
  //     { 80: "80" },
  //     { 90: "90" },
  //     { 100: "100" },
  //     { 120: "120" },
  //     { 140: "140" },
  //     { 160: "160" },
  //     { 180: "180" },
  //     { 200: "200" },
  //   ],
  // },

  first_color: {
    section: "2. Layout",
    type: "array",
    display: "color",
    label: "1. First color",
    default: "#005954",
  },
  second_color: {
    section: "2. Layout",
    type: "array",
    display: "color",
    label: "2. Second color",
    default: "#005954",
  },
  third_color: {
    section: "2. Layout",
    type: "array",
    display: "color",
    label: "3. Third color",
    default: "#005954",
  },
  fourth_color: {
    section: "2. Layout",
    type: "array",
    display: "color",
    label: "4. Fourth color",
    default: "#005954",
  },
  first_dimension: {
    section: "3. Venn",
    type: "string",
    label: "1. Dimension sets",
    default: "",
  },
  second_dimension: {
    section: "3. Venn",
    type: "string",
    label: "2. Dimension size",
    default: "",
  },
  third_dimension: {
    section: "3. Venn",
    type: "string",
    label: "3. Dimension with label",
    default: "",
  },
  fourth_dimension: {
    section: "3. Venn",
    type: "string",
    label: "4. Dimension SUM(total)",
    default: "",
  },
  fifth_dimension: {
    section: "3. Venn",
    type: "string",
    label: "5. Dimension SUM(total) %",
    default: "",
  },
  sixth_dimension: {
    section: "3. Venn",
    type: "string",
    label: "6. Dimension total sent",
    default: "",
  },
};
