export const baseOptions = {
  title_graphic: {
    type: "string",
    label: "Title",
    section: "Base config",
  },
  title_font_size: {
    type: "string",
    label: "Title font size",
    section: "Base config",
  },
  default_icon: {
    type: "string",
    label: "Title Icon <i>",
    default: "",
    section: "Base config",
  },
  measure_title: {
    section: "Layout",
    type: "string",
    label: "Measure title",
    default: "",
  },
  dimension_title: {
    section: "Layout",
    type: "string",
    label: "Dimension title",
    default: "",
  },
  first_dimension: {
    section: "Bar with image",
    type: "string",
    label: "Dimension values",
    default: "",
  },
  second_dimension: {
    section: "Bar with image",
    type: "string",
    label: "Dimension color",
    default: "",
  },
  third_dimension: {
    section: "Bar with image",
    type: "string",
    label: "Dimension with base64 image",
    default: "",
  },
  color_not_selected: {
    section: "Layout",
    type: "array",
    display: "color",
    label: "Color when not selected",
    default: "#dedede",
  },
  side_margin: {
    section: "Layout",
    type: "string",
    label: "Left and right margin of the chart",
    default: "40",
    display: "select",
    values: [
      { 0: "0" },
      { 10: "10" },
      { 20: "20" },
      { 30: "30" },
      { 40: "40" },
      { 50: "50" },
      { 60: "60" },
      { 70: "70" },
      { 80: "80" },
      { 90: "90" },
      { 100: "100" },
      { 120: "120" },
      { 140: "140" },
      { 160: "160" },
      { 180: "180" },
      { 200: "200" },
    ],
  },
  chart_type: {
    type: "string",
    label: "Chart type",
    default: "bar",
    display: "select",
    section: "Base config",
    values: [
      { Bar: "bar" },
      { "Simple Bar": "bar_simple" },
      { Pie: "pie" },
      { Donut: "donut" },
      { "Donut Toggle": "donut_toggle" },
      { Banner: "banner" },
      { Insights: "insights" },
    ],
  },
  font_size_percent: {
    section: "Layout",
    type: "string",
    label: "Percentage font size",
    default: "11",
  },
  stroke_width: {
    section: "Layout",
    type: "string",
    label: "Stroke width",
    display: "select",
    default: "0",
    values: [
      { 0: "0" },
      { 1: "1" },
      { 2: "3" },
      { 3: "3" },
      { 4: "4" },
      { 5: "5" },
      { 6: "6" },
      { 7: "7" },
      { 8: "8" },
      { 9: "9" },
      { 10: "10" },
    ],
  },
  number_format: {
    section: "Format",
    type: "string",
    label: "Number format",
    display: "select",
    default: "normal",
    values: [{ Percent: "percent" }, { Normal: "normal" }],
  },
};
