export const bannerOptions = {
  chart_type: {
    section: "1. Main",
    type: "string",
    label: "1. Chart type",
    default: "bar",
    display: "select",
    values: [
      { Bar: "bar" },
      { "Simple Bar": "bar_simple" },
      { "Pie|Donut": "donut" },
      { Banner: "banner" },
      { Insights: "insights" },
      { "Insights Measures": "insights_measures" },
      { Venn: "venn" },
      { Map: "map" },
      { Table: "bar_horizontal" },
      { "Table DMP": "bar_horizontal_dmp" },
      { "Bar measures only": "bar_simple_measure" },
      { "Button segment": "btn_segment" },
    ],
  },
  title_graphic: {
    section: "1. Main",
    type: "string",
    label: "Title",
  },
  chart_description: {
    section: "1. Main",
    type: "string",
    label: "Chart description",
    default: "",
  },
  title_font_size: {
    section: "2. Layout",
    type: "string",
    label: "Title font size",
  },
  default_icon: {
    section: "2. Layout",
    type: "string",
    label: "Title Icon <i>",
    default: "",
  },
  banner_filter_enabled: {
    section: "2. Layout",
    type: "string",
    display: "select",
    label: "Banner filter enabled",
    default: "no",
    values: [{ Yes: "yes" }, { No: "no" }],
  },
};
