export const tableOptions = {
  chart_type: {
    section: "1. Main",
    type: "string",
    label: "1. Chart type",
    default: "bar",
    display: "select",
    values: [
      { Bar: "bar" },
      { "Simple Bar": "bar_simple" },
      { "Pie|Donut": "donut" },
      { Banner: "banner" },
      { Insights: "insights" },
      { "Insights Measures": "insights_measures" },
      { Venn: "venn" },
      { Map: "map" },
      { Table: "bar_horizontal" },
      { "Table DMP": "bar_horizontal_dmp" },
      { "Bar measures only": "bar_simple_measure" },
      { "Button segment": "btn_segment" },
    ],
  },
  title_graphic: {
    section: "1. Main",
    type: "string",
    label: "2. Title",
  },
  default_icon: {
    section: "1. Main",
    type: "string",
    label: "Title Icon <i>",
    default: "",
  },
  measure_title: {
    section: "1. Main",
    type: "string",
    label: "Measure title",
    default: "",
  },
  dimension_title: {
    section: "1. Main",
    type: "string",
    label: "Dimension title",
    default: "",
  },
  chart_description: {
    section: "1. Main",
    type: "string",
    label: "Chart description",
    default: "",
  },
  color_not_selected: {
    section: "2. Layout",
    type: "array",
    display: "color",
    label: "Color when not selected",
    default: "#dedede",
  },
  color_table: {
    section: "2. Layout",
    type: "array",
    display: "color",
    label: "Color Table",
    default: "#dedede",
  },
  number_format: {
    section: "4. Format",
    type: "string",
    label: "Number format",
    display: "select",
    default: "normal",
    values: [{ Percent: "percent" }, { Normal: "normal" }],
  },
  measure_or_calculation: {
    section: "4. Format",
    type: "string",
    label: "Measure or Calculation",
    display: "select",
    default: "measure",
    values: [{ Measure: "measure" }, { Calculation: "calculation" }],
  },
};
